#!/bin/sh     
ssh -o StrictHostKeyChecking=no ubuntu@13.213.31.98 <<EOF
   cd /var/www/jenkins-nodejs-sample-project
   git pull origin master
   npm install 
   npm i -g pm2
   pm2 restart all
   exit
EOF