#!/bin/sh     
ssh -tt-o StrictHostKeyChecking=no ubuntu@13.213.31.98 <<EOF
   cd /var/www/jenkins-nodejs-sample-project
   git pull origin master
   npm install --production
   npm i -g pm2
   pm2 restart all
   exit
EOF